<?php
//現在の日時を取得
$datetime = date('m-d');

if ($datetime >= '02-04' && $datetime < '02-18') {
  $season = "spring";
  $seasonName = "立春（りっしゅん）";
  $seasonID = "risshun";
} elseif ($datetime >= '02-19' && $datetime < '03-04') {
  $season = "spring";
  $seasonName = "雨水（うすい）";
  $seasonID = "usui";
} elseif ($datetime >= '03-05' && $datetime < '03-19') {
  $season = "spring";
  $seasonName = "啓蟄（けいちつ）";
  $seasonID = "keichitsu";
} elseif ($datetime >= '03-20' && $datetime < '04-03') {
  $season = "spring";
  $seasonName = "春分（しゅんぶん）";
  $seasonID = "shunbun";
} elseif ($datetime >= '04-04' && $datetime < '04-18') {
  $season = "spring";
  $seasonName = "清明（せいめい）";
  $seasonID = "seimei";
} elseif ($datetime >= '04-19' && $datetime < '05-04') {
  $season = "spring";
  $seasonName = "穀雨（こくう）";
  $seasonID = "kokuu";
} elseif ($datetime >= '05-05' && $datetime < '05-19') {
  $season = "summer";
  $seasonName = "立夏（りっか）";
  $seasonID = "rikka";
} elseif ($datetime >= '05-20' && $datetime < '06-04') {
  $season = "summer";
  $seasonName = "小満（しょうまん）";
  $seasonID = "shouman";
} elseif ($datetime >= '06-05' && $datetime < '06-20') {
  $season = "summer";
  $seasonName = "芒種（ぼうしゅ）";
  $seasonID = "boushu";
} elseif ($datetime >= '06-21' && $datetime < '07-06') {
  $season = "summer";
  $seasonName = "夏至（げし）";
  $seasonID = "geshi";
} elseif ($datetime >= '07-07' && $datetime < '07-22') {
  $season = "summer";
  $seasonName = "小暑（しょうしょ）";
  $seasonID = "shousho";
} elseif ($datetime >= '07-23' && $datetime < '08-07') {
  $season = "summer";
  $seasonName = "大暑（たいしょ）";
  $seasonID = "taisho";
} elseif ($datetime >= '08-08' && $datetime < '08-22') {
  $season = "autumn";
  $seasonName = "立秋（りっしゅう）";
  $seasonID = "risshu";
} elseif ($datetime >= '08-21' && $datetime < '09-07') {
  $season = "autumn";
  $seasonName = "処暑（しょしょ）";
  $seasonID = "shosho";
} elseif ($datetime >= '09-08' && $datetime < '09-22') {
  $season = "autumn";
  $seasonName = "白露（はくろ）";
  $seasonID = "hakuro";
} elseif ($datetime >= '09-23' && $datetime < '10-07') {
  $season = "autumn";
  $seasonName = "秋分（しゅうぶん）";
  $seasonID = "shuubun";
} elseif ($datetime >= '10-08' && $datetime < '10-23') {
  $season = "autumn";
  $seasonName = "寒露（かんろ）";
  $seasonID = "kanro";
} elseif ($datetime >= '10-24' && $datetime < '11-07') {
  $season = "autumn";
  $seasonName = "霜降（そうこう）";
  $seasonID = "soukou";
} elseif ($datetime >= '11-08' && $datetime < '11-21') {
  $season = "winter";
  $seasonName = "立冬（りっとう）";
  $seasonID = "rittou";
} elseif ($datetime >= '11-22' && $datetime < '12-06') {
  $season = "winter";
  $seasonName = "小雪（しょうせつ）";
  $seasonID = "shousetsu";
} elseif ($datetime >= '12-07' && $datetime < '12-21') {
  $season = "winter";
  $seasonName = "大雪（たいせつ）";
  $seasonID = "taisetsu";
} elseif ($datetime >= '12-22' && $datetime < '01-05') {
  $season = "winter";
  $seasonName = "冬至（とうじ）";
  $seasonID = "touji";
} elseif ($datetime >= '01-06' && $datetime < '01-19') {
  $season = "winter";
  $seasonName = "小寒（しょうかん）";
  $seasonID = "shoukan";
} elseif ($datetime >= '01-20' && $datetime < '02-03') {
  $season = "winter";
  $seasonName = "大寒（だいかん）";
  $seasonID = "daikan";
}
?>
